name: Build DLL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Download CS2 Dumper Offsets
      run: |
        git clone --depth 1 https://github.com/a2x/cs2-dumper.git dumper
        New-Item -ItemType Directory -Force -Path D:\cs2\output
        Copy-Item -Path dumper\output\* -Destination D:\cs2\output -Recurse

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -A x64
      working-directory: ./Internal

    - name: Build
      run: cmake --build build --config Release
      working-directory: ./Internal

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: cs2_internal_dll
        path: Internal/build/Release/*.dll
