name: Build DLL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore "Internal/X0reca CG Internal.vcxproj"

    - name: Build with MSBuild
      run: msbuild "Internal/X0reca CG Internal.vcxproj" /p:Configuration=Release /p:Platform=x64

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: cs2_internal_dll
        path: Internal/x64/Release/*.dll
